services:
  - type: web
    name: n8n-core
    env: node
    plan: starter
    branch: main
    region: singapore
    numInstances: 1
    healthCheckPath: /healthz
    envVars:
      - key: DB_TYPE
        value: sqlite
      - key: N8N_BASIC_AUTH_USER
        value: ajit
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Khandekar@6622!!
      - key: WEBHOOK_URL
        value: https://n8n-core.onrender.com
      - key: N8N_ENCRYPTION_KEY
        value: J3Xj9<<i(Rm:kD+(
      - key: N8N_USER_MANAGEMENT_DISABLED
        value: 'true'
      - key: N8N_HOST
        value: 0.0.0.0
      - key: N8N_PORT
        value: 5678
      - key: DB_SQLITE_DATABASE
        value: /data/n8n.sqlite


